services:
  db:
    build:
      context: ./db
    container_name: innovatech-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: tienda_perritos
      MYSQL_USER: alumno
      MYSQL_PASSWORD: alumno123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - innovatech-net

  backend:
    build:
      context: ./backend
    container_name: innovatech-backend
    restart: always
    environment:
      PORT: 3001
      DB_HOST: db
      DB_USER: alumno
      DB_PASSWORD: alumno123
      DB_NAME: tienda_perritos
      DB_PORT: 3306
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - innovatech-net

volumes:
  mysql_data:

networks:
  innovatech-net:
    driver: bridge